#!/bin/bash
inputinfo=$1
if [ "$inputinfo" = "" ]; then
/root/bcdn/bcdn.sh start
echo "已启动bcdn矿机"
else
echo -ne "$inputinfo" > /root/bcdn/conf/code.txt
echo "已添加挖矿码 $inputinfo"
/root/bcdn/bcdn.sh start
/root/bcdn/bcdn.sh log
fi

