#!/bin/bash
inputinfo=$1
if [ "$inputinfo" = "" ]; then
cd /root/bcdn/BerryMiner_v1_0/server
./bcdn_check.sh
echo "已启动bcdn矿机"
else
echo -ne "$inputinfo" > /root/bcdn/BerryMiner_v1_0/server/conf/code.txt
echo "已添加挖矿码 $inputinfo"
cd /root/bcdn/BerryMiner_v1_0/server
./bcdn_check.sh
fi
